//! Typed Search Evidence Graph edges.

use crate::{AbsoluteUrl, Evidence};
use serde::{Deserialize, Serialize};

/// Relation between two search-surface nodes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Relation {
    /// Internal or extracted hyperlink.
    LinksTo,
    /// Canonical target.
    CanonicalTo,
    /// Hreflang alternate.
    AlternateOf,
    /// Redirect.
    RedirectsTo,
    /// Listed in a sitemap.
    ListedInSitemap,
    /// Blocked by robots.
    BlockedBy,
    /// Live URL is rendered by a route family.
    RenderedBy,
    /// Route or URL is generated by a source symbol.
    GeneratedBy,
    /// Metadata comes from a source symbol or data field.
    MetadataFrom,
    /// URL declares a schema object.
    Declares,
    /// URL publishes a typed claim.
    Claims,
    /// URL is about an entity, topic, or market.
    About,
    /// Claim or activity requires a credential or legal fact.
    Requires,
    /// Observation attached to a URL.
    ObservedAs,
    /// Node was changed by a revision. Requires proof that the revision produced it.
    ChangedBy,
    /// Measured live evidence was compared against a source revision.
    ///
    /// This is the honest relation for a hybrid run: the crawl saw production,
    /// the worktree is at some revision, and nothing proves production was
    /// built from it. Upgrade to [`Relation::ChangedBy`] only with deployment
    /// or build evidence.
    ComparedAgainst,
}

/// One recorded graph edge.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GraphEdge {
    /// Source URL.
    pub source: AbsoluteUrl,
    /// Target URL.
    pub target: AbsoluteUrl,
    /// Relation.
    pub relation: Relation,
    /// Evidence for the relation.
    pub evidence: Evidence,
    /// Anchor text when the relation is a hyperlink.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub anchor: Option<String>,
    /// `rel` tokens joined by space.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rel: Option<String>,
    /// Document location of the link.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub location: Option<crate::LinkLocation>,
    /// Surrounding context.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    /// How often this link shape repeats across templates. `None` if unique.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub template_frequency: Option<u32>,
}

impl GraphEdge {
    /// Builds a relation edge.
    #[must_use]
    pub fn new(
        source: AbsoluteUrl,
        target: AbsoluteUrl,
        relation: Relation,
        evidence: Evidence,
    ) -> Self {
        Self {
            source,
            target,
            relation,
            evidence,
            anchor: None,
            rel: None,
            location: None,
            context: None,
            template_frequency: None,
        }
    }

    /// Attaches hyperlink semantics.
    #[must_use]
    pub fn with_link(
        mut self,
        anchor: Option<String>,
        rel: Option<String>,
        location: Option<crate::LinkLocation>,
        context: Option<String>,
    ) -> Self {
        self.anchor = anchor;
        self.rel = rel;
        self.location = location;
        self.context = context;
        self
    }
}
